# Nextcloud installation for ansible
---
- hosts: ubuntu
  remote_user: vagrant
  become: yes
  become_method: "sudo"

  tasks:
    - name: Download nextcloud
      get_url:
        url: https://download.nextcloud.com/server/releases/nextcloud-18.0.3.zip
        dest: /var/www/html/
        
    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: /var/www/html/nextcloud-18.0.3.zip
        dest: /var/www/html/nextcloud/
        remote_src: yes
       
    - name: Set rights on nextcloud directory
      file:
        path: /var/www/html/nextcloud/
        state: directory
        mode: '0755'
        recurse: yes
        owner: nobody
        group: nogroup
